ln -sf ./busybox [
ln -sf ./busybox [[
ln -sf ./busybox acpid
ln -sf ./busybox adjtimex
ln -sf ./busybox ar
ln -sf ./busybox arch
ln -sf ./busybox arp
ln -sf ./busybox arping
ln -sf ./busybox ash
ln -sf ./busybox awk
ln -sf ./busybox basename
ln -sf ./busybox bc
ln -sf ./busybox blkdiscard
ln -sf ./busybox blockdev
ln -sf ./busybox brctl
ln -sf ./busybox bunzip2
ln -sf ./busybox bzcat
ln -sf ./busybox bzip2
ln -sf ./busybox cal
ln -sf ./busybox cat
ln -sf ./busybox chgrp
ln -sf ./busybox chmod
ln -sf ./busybox chown
ln -sf ./busybox chpasswd
ln -sf ./busybox chroot
ln -sf ./busybox chvt
ln -sf ./busybox clear
ln -sf ./busybox cmp
ln -sf ./busybox cp
ln -sf ./busybox cpio
ln -sf ./busybox crond
ln -sf ./busybox crontab
ln -sf ./busybox cttyhack
ln -sf ./busybox cut
ln -sf ./busybox date
ln -sf ./busybox dc
ln -sf ./busybox dd
ln -sf ./busybox deallocvt
ln -sf ./busybox depmod
ln -sf ./busybox devmem
ln -sf ./busybox df
ln -sf ./busybox diff
ln -sf ./busybox dirname
ln -sf ./busybox dmesg
ln -sf ./busybox dnsdomainname
ln -sf ./busybox dos2unix
ln -sf ./busybox dpkg
ln -sf ./busybox dpkg-deb
ln -sf ./busybox du
ln -sf ./busybox dumpkmap
ln -sf ./busybox dumpleases
ln -sf ./busybox echo
ln -sf ./busybox ed
ln -sf ./busybox egrep
ln -sf ./busybox env
ln -sf ./busybox expand
ln -sf ./busybox expr
ln -sf ./busybox factor
ln -sf ./busybox fallocate
ln -sf ./busybox false
ln -sf ./busybox fatattr
ln -sf ./busybox fdisk
ln -sf ./busybox fgrep
ln -sf ./busybox find
ln -sf ./busybox fold
ln -sf ./busybox free
ln -sf ./busybox freeramdisk
ln -sf ./busybox fsfreeze
ln -sf ./busybox fstrim
ln -sf ./busybox ftpget
ln -sf ./busybox ftpput
ln -sf ./busybox getopt
ln -sf ./busybox getty
ln -sf ./busybox grep
ln -sf ./busybox groups
ln -sf ./busybox gunzip
ln -sf ./busybox gzip
ln -sf ./busybox halt
ln -sf ./busybox head
ln -sf ./busybox hexdump
ln -sf ./busybox hostid
ln -sf ./busybox hostname
ln -sf ./busybox httpd
ln -sf ./busybox hwclock
ln -sf ./busybox i2cdetect
ln -sf ./busybox i2cdump
ln -sf ./busybox i2cget
ln -sf ./busybox i2cset
ln -sf ./busybox id
ln -sf ./busybox ifconfig
ln -sf ./busybox ifdown
ln -sf ./busybox ifup
ln -sf ./busybox init
ln -sf ./busybox insmod
ln -sf ./busybox ionice
ln -sf ./busybox ip
ln -sf ./busybox ipcalc
ln -sf ./busybox ipneigh
ln -sf ./busybox kill
ln -sf ./busybox killall
ln -sf ./busybox klogd
ln -sf ./busybox last
ln -sf ./busybox less
ln -sf ./busybox link
ln -sf ./busybox linux32
ln -sf ./busybox linux64
ln -sf ./busybox linuxrc
ln -sf ./busybox ln
ln -sf ./busybox loadfont
ln -sf ./busybox loadkmap
ln -sf ./busybox logger
ln -sf ./busybox login
ln -sf ./busybox logname
ln -sf ./busybox logread
ln -sf ./busybox losetup
ln -sf ./busybox ls
ln -sf ./busybox lsmod
ln -sf ./busybox lsscsi
ln -sf ./busybox lzcat
ln -sf ./busybox lzma
ln -sf ./busybox lzop
ln -sf ./busybox md5sum
ln -sf ./busybox mdev
ln -sf ./busybox microcom
ln -sf ./busybox mkdir
ln -sf ./busybox mkdosfs
ln -sf ./busybox mke2fs
ln -sf ./busybox mkfifo
ln -sf ./busybox mknod
ln -sf ./busybox mkpasswd
ln -sf ./busybox mkswap
ln -sf ./busybox mktemp
ln -sf ./busybox modinfo
ln -sf ./busybox modprobe
ln -sf ./busybox more
ln -sf ./busybox mount
ln -sf ./busybox mt
ln -sf ./busybox mv
ln -sf ./busybox nameif
ln -sf ./busybox nc
ln -sf ./busybox netstat
ln -sf ./busybox nl
ln -sf ./busybox nologin
ln -sf ./busybox nproc
ln -sf ./busybox nsenter
ln -sf ./busybox nslookup
ln -sf ./busybox nuke
ln -sf ./busybox od
ln -sf ./busybox openvt
ln -sf ./busybox partprobe
ln -sf ./busybox passwd
ln -sf ./busybox paste
ln -sf ./busybox patch
ln -sf ./busybox pidof
ln -sf ./busybox ping
ln -sf ./busybox ping6
ln -sf ./busybox pivot_root
ln -sf ./busybox poweroff
ln -sf ./busybox printf
ln -sf ./busybox ps
ln -sf ./busybox pwd
ln -sf ./busybox rdate
ln -sf ./busybox readlink
ln -sf ./busybox realpath
ln -sf ./busybox reboot
ln -sf ./busybox renice
ln -sf ./busybox reset
ln -sf ./busybox resume
ln -sf ./busybox rev
ln -sf ./busybox rm
ln -sf ./busybox rmdir
ln -sf ./busybox rmmod
ln -sf ./busybox route
ln -sf ./busybox rpm
ln -sf ./busybox rpm2cpio
ln -sf ./busybox run-init
ln -sf ./busybox run-parts
ln -sf ./busybox sed
ln -sf ./busybox seq
ln -sf ./busybox setkeycodes
ln -sf ./busybox setpriv
ln -sf ./busybox setsid
ln -sf ./busybox sh
ln -sf ./busybox sha1sum
ln -sf ./busybox sha256sum
ln -sf ./busybox sha512sum
ln -sf ./busybox shred
ln -sf ./busybox shuf
ln -sf ./busybox sleep
ln -sf ./busybox sort
ln -sf ./busybox ssl_client
ln -sf ./busybox start-stop-daemon
ln -sf ./busybox stat
ln -sf ./busybox static-sh
ln -sf ./busybox strings
ln -sf ./busybox stty
ln -sf ./busybox su
ln -sf ./busybox sulogin
ln -sf ./busybox svc
ln -sf ./busybox svok
ln -sf ./busybox swapoff
ln -sf ./busybox swapon
ln -sf ./busybox switch_root
ln -sf ./busybox sync
ln -sf ./busybox sysctl
ln -sf ./busybox syslogd
ln -sf ./busybox tac
ln -sf ./busybox tail
ln -sf ./busybox tar
ln -sf ./busybox taskset
ln -sf ./busybox tc
ln -sf ./busybox tee
ln -sf ./busybox telnet
ln -sf ./busybox telnetd
ln -sf ./busybox test
ln -sf ./busybox tftp
ln -sf ./busybox time
ln -sf ./busybox timeout
ln -sf ./busybox top
ln -sf ./busybox touch
ln -sf ./busybox tr
ln -sf ./busybox traceroute
ln -sf ./busybox traceroute6
ln -sf ./busybox true
ln -sf ./busybox truncate
ln -sf ./busybox tty
ln -sf ./busybox tunctl
ln -sf ./busybox ubirename
ln -sf ./busybox udhcpc
ln -sf ./busybox udhcpd
ln -sf ./busybox uevent
ln -sf ./busybox umount
ln -sf ./busybox uname
ln -sf ./busybox uncompress
ln -sf ./busybox unexpand
ln -sf ./busybox uniq
ln -sf ./busybox unix2dos
ln -sf ./busybox unlink
ln -sf ./busybox unlzma
ln -sf ./busybox unshare
ln -sf ./busybox unxz
ln -sf ./busybox unzip
ln -sf ./busybox uptime
ln -sf ./busybox usleep
ln -sf ./busybox uudecode
ln -sf ./busybox uuencode
ln -sf ./busybox vconfig
ln -sf ./busybox vi
ln -sf ./busybox w
ln -sf ./busybox watch
ln -sf ./busybox watchdog
ln -sf ./busybox wc
ln -sf ./busybox wget
ln -sf ./busybox which
ln -sf ./busybox who
ln -sf ./busybox whoami
ln -sf ./busybox xargs
ln -sf ./busybox xxd
ln -sf ./busybox xz
ln -sf ./busybox xzcat
ln -sf ./busybox yes
ln -sf ./busybox zcat
