echo '/busybox/busybox [ $*' > scripts/[
echo '/busybox/busybox [[ $*' > scripts/[[
echo '/busybox/busybox acpid $*' > scripts/acpid
echo '/busybox/busybox adjtimex $*' > scripts/adjtimex
echo '/busybox/busybox ar $*' > scripts/ar
echo '/busybox/busybox arch $*' > scripts/arch
echo '/busybox/busybox arp $*' > scripts/arp
echo '/busybox/busybox arping $*' > scripts/arping
echo '/busybox/busybox ash $*' > scripts/ash
echo '/busybox/busybox awk $*' > scripts/awk
echo '/busybox/busybox basename $*' > scripts/basename
echo '/busybox/busybox bc $*' > scripts/bc
echo '/busybox/busybox blkdiscard $*' > scripts/blkdiscard
echo '/busybox/busybox blockdev $*' > scripts/blockdev
echo '/busybox/busybox brctl $*' > scripts/brctl
echo '/busybox/busybox bunzip2 $*' > scripts/bunzip2
echo '/busybox/busybox bzcat $*' > scripts/bzcat
echo '/busybox/busybox bzip2 $*' > scripts/bzip2
echo '/busybox/busybox cal $*' > scripts/cal
echo '/busybox/busybox cat $*' > scripts/cat
echo '/busybox/busybox chgrp $*' > scripts/chgrp
echo '/busybox/busybox chmod $*' > scripts/chmod
echo '/busybox/busybox chown $*' > scripts/chown
echo '/busybox/busybox chpasswd $*' > scripts/chpasswd
echo '/busybox/busybox chroot $*' > scripts/chroot
echo '/busybox/busybox chvt $*' > scripts/chvt
echo '/busybox/busybox clear $*' > scripts/clear
echo '/busybox/busybox cmp $*' > scripts/cmp
echo '/busybox/busybox cp $*' > scripts/cp
echo '/busybox/busybox cpio $*' > scripts/cpio
echo '/busybox/busybox crond $*' > scripts/crond
echo '/busybox/busybox crontab $*' > scripts/crontab
echo '/busybox/busybox cttyhack $*' > scripts/cttyhack
echo '/busybox/busybox cut $*' > scripts/cut
echo '/busybox/busybox date $*' > scripts/date
echo '/busybox/busybox dc $*' > scripts/dc
echo '/busybox/busybox dd $*' > scripts/dd
echo '/busybox/busybox deallocvt $*' > scripts/deallocvt
echo '/busybox/busybox depmod $*' > scripts/depmod
echo '/busybox/busybox devmem $*' > scripts/devmem
echo '/busybox/busybox df $*' > scripts/df
echo '/busybox/busybox diff $*' > scripts/diff
echo '/busybox/busybox dirname $*' > scripts/dirname
echo '/busybox/busybox dmesg $*' > scripts/dmesg
echo '/busybox/busybox dnsdomainname $*' > scripts/dnsdomainname
echo '/busybox/busybox dos2unix $*' > scripts/dos2unix
echo '/busybox/busybox dpkg $*' > scripts/dpkg
echo '/busybox/busybox dpkg-deb $*' > scripts/dpkg-deb
echo '/busybox/busybox du $*' > scripts/du
echo '/busybox/busybox dumpkmap $*' > scripts/dumpkmap
echo '/busybox/busybox dumpleases $*' > scripts/dumpleases
echo '/busybox/busybox echo $*' > scripts/echo
echo '/busybox/busybox ed $*' > scripts/ed
echo '/busybox/busybox egrep $*' > scripts/egrep
echo '/busybox/busybox env $*' > scripts/env
echo '/busybox/busybox expand $*' > scripts/expand
echo '/busybox/busybox expr $*' > scripts/expr
echo '/busybox/busybox factor $*' > scripts/factor
echo '/busybox/busybox fallocate $*' > scripts/fallocate
echo '/busybox/busybox false $*' > scripts/false
echo '/busybox/busybox fatattr $*' > scripts/fatattr
echo '/busybox/busybox fdisk $*' > scripts/fdisk
echo '/busybox/busybox fgrep $*' > scripts/fgrep
echo '/busybox/busybox find $*' > scripts/find
echo '/busybox/busybox fold $*' > scripts/fold
echo '/busybox/busybox free $*' > scripts/free
echo '/busybox/busybox freeramdisk $*' > scripts/freeramdisk
echo '/busybox/busybox fsfreeze $*' > scripts/fsfreeze
echo '/busybox/busybox fstrim $*' > scripts/fstrim
echo '/busybox/busybox ftpget $*' > scripts/ftpget
echo '/busybox/busybox ftpput $*' > scripts/ftpput
echo '/busybox/busybox getopt $*' > scripts/getopt
echo '/busybox/busybox getty $*' > scripts/getty
echo '/busybox/busybox grep $*' > scripts/grep
echo '/busybox/busybox groups $*' > scripts/groups
echo '/busybox/busybox gunzip $*' > scripts/gunzip
echo '/busybox/busybox gzip $*' > scripts/gzip
echo '/busybox/busybox halt $*' > scripts/halt
echo '/busybox/busybox head $*' > scripts/head
echo '/busybox/busybox hexdump $*' > scripts/hexdump
echo '/busybox/busybox hostid $*' > scripts/hostid
echo '/busybox/busybox hostname $*' > scripts/hostname
echo '/busybox/busybox httpd $*' > scripts/httpd
echo '/busybox/busybox hwclock $*' > scripts/hwclock
echo '/busybox/busybox i2cdetect $*' > scripts/i2cdetect
echo '/busybox/busybox i2cdump $*' > scripts/i2cdump
echo '/busybox/busybox i2cget $*' > scripts/i2cget
echo '/busybox/busybox i2cset $*' > scripts/i2cset
echo '/busybox/busybox id $*' > scripts/id
echo '/busybox/busybox ifconfig $*' > scripts/ifconfig
echo '/busybox/busybox ifdown $*' > scripts/ifdown
echo '/busybox/busybox ifup $*' > scripts/ifup
echo '/busybox/busybox init $*' > scripts/init
echo '/busybox/busybox insmod $*' > scripts/insmod
echo '/busybox/busybox ionice $*' > scripts/ionice
echo '/busybox/busybox ip $*' > scripts/ip
echo '/busybox/busybox ipcalc $*' > scripts/ipcalc
echo '/busybox/busybox ipneigh $*' > scripts/ipneigh
echo '/busybox/busybox kill $*' > scripts/kill
echo '/busybox/busybox killall $*' > scripts/killall
echo '/busybox/busybox klogd $*' > scripts/klogd
echo '/busybox/busybox last $*' > scripts/last
echo '/busybox/busybox less $*' > scripts/less
echo '/busybox/busybox link $*' > scripts/link
echo '/busybox/busybox linux32 $*' > scripts/linux32
echo '/busybox/busybox linux64 $*' > scripts/linux64
echo '/busybox/busybox linuxrc $*' > scripts/linuxrc
echo '/busybox/busybox ln $*' > scripts/ln
echo '/busybox/busybox loadfont $*' > scripts/loadfont
echo '/busybox/busybox loadkmap $*' > scripts/loadkmap
echo '/busybox/busybox logger $*' > scripts/logger
echo '/busybox/busybox login $*' > scripts/login
echo '/busybox/busybox logname $*' > scripts/logname
echo '/busybox/busybox logread $*' > scripts/logread
echo '/busybox/busybox losetup $*' > scripts/losetup
echo '/busybox/busybox ls $*' > scripts/ls
echo '/busybox/busybox lsmod $*' > scripts/lsmod
echo '/busybox/busybox lsscsi $*' > scripts/lsscsi
echo '/busybox/busybox lzcat $*' > scripts/lzcat
echo '/busybox/busybox lzma $*' > scripts/lzma
echo '/busybox/busybox lzop $*' > scripts/lzop
echo '/busybox/busybox md5sum $*' > scripts/md5sum
echo '/busybox/busybox mdev $*' > scripts/mdev
echo '/busybox/busybox microcom $*' > scripts/microcom
echo '/busybox/busybox mkdir $*' > scripts/mkdir
echo '/busybox/busybox mkdosfs $*' > scripts/mkdosfs
echo '/busybox/busybox mke2fs $*' > scripts/mke2fs
echo '/busybox/busybox mkfifo $*' > scripts/mkfifo
echo '/busybox/busybox mknod $*' > scripts/mknod
echo '/busybox/busybox mkpasswd $*' > scripts/mkpasswd
echo '/busybox/busybox mkswap $*' > scripts/mkswap
echo '/busybox/busybox mktemp $*' > scripts/mktemp
echo '/busybox/busybox modinfo $*' > scripts/modinfo
echo '/busybox/busybox modprobe $*' > scripts/modprobe
echo '/busybox/busybox more $*' > scripts/more
echo '/busybox/busybox mount $*' > scripts/mount
echo '/busybox/busybox mt $*' > scripts/mt
echo '/busybox/busybox mv $*' > scripts/mv
echo '/busybox/busybox nameif $*' > scripts/nameif
echo '/busybox/busybox nc $*' > scripts/nc
echo '/busybox/busybox netstat $*' > scripts/netstat
echo '/busybox/busybox nl $*' > scripts/nl
echo '/busybox/busybox nologin $*' > scripts/nologin
echo '/busybox/busybox nproc $*' > scripts/nproc
echo '/busybox/busybox nsenter $*' > scripts/nsenter
echo '/busybox/busybox nslookup $*' > scripts/nslookup
echo '/busybox/busybox nuke $*' > scripts/nuke
echo '/busybox/busybox od $*' > scripts/od
echo '/busybox/busybox openvt $*' > scripts/openvt
echo '/busybox/busybox partprobe $*' > scripts/partprobe
echo '/busybox/busybox passwd $*' > scripts/passwd
echo '/busybox/busybox paste $*' > scripts/paste
echo '/busybox/busybox patch $*' > scripts/patch
echo '/busybox/busybox pidof $*' > scripts/pidof
echo '/busybox/busybox ping $*' > scripts/ping
echo '/busybox/busybox ping6 $*' > scripts/ping6
echo '/busybox/busybox pivot_root $*' > scripts/pivot_root
echo '/busybox/busybox poweroff $*' > scripts/poweroff
echo '/busybox/busybox printf $*' > scripts/printf
echo '/busybox/busybox ps $*' > scripts/ps
echo '/busybox/busybox pwd $*' > scripts/pwd
echo '/busybox/busybox rdate $*' > scripts/rdate
echo '/busybox/busybox readlink $*' > scripts/readlink
echo '/busybox/busybox realpath $*' > scripts/realpath
echo '/busybox/busybox reboot $*' > scripts/reboot
echo '/busybox/busybox renice $*' > scripts/renice
echo '/busybox/busybox reset $*' > scripts/reset
echo '/busybox/busybox resume $*' > scripts/resume
echo '/busybox/busybox rev $*' > scripts/rev
echo '/busybox/busybox rm $*' > scripts/rm
echo '/busybox/busybox rmdir $*' > scripts/rmdir
echo '/busybox/busybox rmmod $*' > scripts/rmmod
echo '/busybox/busybox route $*' > scripts/route
echo '/busybox/busybox rpm $*' > scripts/rpm
echo '/busybox/busybox rpm2cpio $*' > scripts/rpm2cpio
echo '/busybox/busybox run-init $*' > scripts/run-init
echo '/busybox/busybox run-parts $*' > scripts/run-parts
echo '/busybox/busybox sed $*' > scripts/sed
echo '/busybox/busybox seq $*' > scripts/seq
echo '/busybox/busybox setkeycodes $*' > scripts/setkeycodes
echo '/busybox/busybox setpriv $*' > scripts/setpriv
echo '/busybox/busybox setsid $*' > scripts/setsid
echo '/busybox/busybox sh $*' > scripts/sh
echo '/busybox/busybox sha1sum $*' > scripts/sha1sum
echo '/busybox/busybox sha256sum $*' > scripts/sha256sum
echo '/busybox/busybox sha512sum $*' > scripts/sha512sum
echo '/busybox/busybox shred $*' > scripts/shred
echo '/busybox/busybox shuf $*' > scripts/shuf
echo '/busybox/busybox sleep $*' > scripts/sleep
echo '/busybox/busybox sort $*' > scripts/sort
echo '/busybox/busybox ssl_client $*' > scripts/ssl_client
echo '/busybox/busybox start-stop-daemon $*' > scripts/start-stop-daemon
echo '/busybox/busybox stat $*' > scripts/stat
echo '/busybox/busybox static-sh $*' > scripts/static-sh
echo '/busybox/busybox strings $*' > scripts/strings
echo '/busybox/busybox stty $*' > scripts/stty
echo '/busybox/busybox su $*' > scripts/su
echo '/busybox/busybox sulogin $*' > scripts/sulogin
echo '/busybox/busybox svc $*' > scripts/svc
echo '/busybox/busybox svok $*' > scripts/svok
echo '/busybox/busybox swapoff $*' > scripts/swapoff
echo '/busybox/busybox swapon $*' > scripts/swapon
echo '/busybox/busybox switch_root $*' > scripts/switch_root
echo '/busybox/busybox sync $*' > scripts/sync
echo '/busybox/busybox sysctl $*' > scripts/sysctl
echo '/busybox/busybox syslogd $*' > scripts/syslogd
echo '/busybox/busybox tac $*' > scripts/tac
echo '/busybox/busybox tail $*' > scripts/tail
echo '/busybox/busybox tar $*' > scripts/tar
echo '/busybox/busybox taskset $*' > scripts/taskset
echo '/busybox/busybox tc $*' > scripts/tc
echo '/busybox/busybox tee $*' > scripts/tee
echo '/busybox/busybox telnet $*' > scripts/telnet
echo '/busybox/busybox telnetd $*' > scripts/telnetd
echo '/busybox/busybox test $*' > scripts/test
echo '/busybox/busybox tftp $*' > scripts/tftp
echo '/busybox/busybox time $*' > scripts/time
echo '/busybox/busybox timeout $*' > scripts/timeout
echo '/busybox/busybox top $*' > scripts/top
echo '/busybox/busybox touch $*' > scripts/touch
echo '/busybox/busybox tr $*' > scripts/tr
echo '/busybox/busybox traceroute $*' > scripts/traceroute
echo '/busybox/busybox traceroute6 $*' > scripts/traceroute6
echo '/busybox/busybox true $*' > scripts/true
echo '/busybox/busybox truncate $*' > scripts/truncate
echo '/busybox/busybox tty $*' > scripts/tty
echo '/busybox/busybox tunctl $*' > scripts/tunctl
echo '/busybox/busybox ubirename $*' > scripts/ubirename
echo '/busybox/busybox udhcpc $*' > scripts/udhcpc
echo '/busybox/busybox udhcpd $*' > scripts/udhcpd
echo '/busybox/busybox uevent $*' > scripts/uevent
echo '/busybox/busybox umount $*' > scripts/umount
echo '/busybox/busybox uname $*' > scripts/uname
echo '/busybox/busybox uncompress $*' > scripts/uncompress
echo '/busybox/busybox unexpand $*' > scripts/unexpand
echo '/busybox/busybox uniq $*' > scripts/uniq
echo '/busybox/busybox unix2dos $*' > scripts/unix2dos
echo '/busybox/busybox unlink $*' > scripts/unlink
echo '/busybox/busybox unlzma $*' > scripts/unlzma
echo '/busybox/busybox unshare $*' > scripts/unshare
echo '/busybox/busybox unxz $*' > scripts/unxz
echo '/busybox/busybox unzip $*' > scripts/unzip
echo '/busybox/busybox uptime $*' > scripts/uptime
echo '/busybox/busybox usleep $*' > scripts/usleep
echo '/busybox/busybox uudecode $*' > scripts/uudecode
echo '/busybox/busybox uuencode $*' > scripts/uuencode
echo '/busybox/busybox vconfig $*' > scripts/vconfig
echo '/busybox/busybox vi $*' > scripts/vi
echo '/busybox/busybox w $*' > scripts/w
echo '/busybox/busybox watch $*' > scripts/watch
echo '/busybox/busybox watchdog $*' > scripts/watchdog
echo '/busybox/busybox wc $*' > scripts/wc
echo '/busybox/busybox wget $*' > scripts/wget
echo '/busybox/busybox which $*' > scripts/which
echo '/busybox/busybox who $*' > scripts/who
echo '/busybox/busybox whoami $*' > scripts/whoami
echo '/busybox/busybox xargs $*' > scripts/xargs
echo '/busybox/busybox xxd $*' > scripts/xxd
echo '/busybox/busybox xz $*' > scripts/xz
echo '/busybox/busybox xzcat $*' > scripts/xzcat
echo '/busybox/busybox yes $*' > scripts/yes
echo '/busybox/busybox zcat $*' > scripts/zcat
